server {
    listen 3000;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Explicit MIME Types
    include /etc/nginx/mime.types;
    types {
        text/css css;
        application/javascript js;
        application/json json;
        image/svg+xml svg;
        image/png png;
        image/jpeg jpg jpeg;
        font/woff woff;
        font/woff2 woff2;
    }

    # Logging
    access_log /dev/stdout;
    error_log /dev/stderr info;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/javascript application/json;

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    # Static Assets & Public Files
    location ~* \.(?:css|js|json|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        try_files $uri =404;
        expires 1y;
        add_header Cache-Control "public";
    }

    # SPA Routing Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # No cache for index.html
    location = /index.html {
        expires -1;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }
}
